export const ACTION_ORDERS_GET_STARTED = 'ACTION_ORDERS_GET_STARTED'
export const ACTION_ORDERS_GET_SUCCESS = 'ACTION_ORDERS_GET_SUCCESS'
export const ACTION_ORDERS_GET_FAILED = 'ACTION_ORDERS_GET_FAILED'
