export const ACTION_GET_CATEGORIOS_STARTED = 'ACTION_GET_CATEGORIOS_STARTED'
export const ACTION_GET_CATEGORIOS_SUCCESED = 'ACTION_GET_CATEGORIOS_SUCCESED'
export const ACTION_GET_CATEGORIOS_FAILED = 'ACTION_GET_CATEGORIOS_FAILED'

export const ACTION_GET_CITY_SUCCESED = 'ACTION_GET_CITY_SUCCESED'
export const ACTION_GET_CITY_FAILED = 'ACTION_GET_CITY_FAILED'

export const ACTION_GET_SLIDER_SUCCESED = 'ACTION_GET_SLIDER_SUCCESED'
export const ACTION_GET_SLIDER_FAILED = 'ACTION_GET_SLIDER_FAILED'
