export const ACTION_GET_ITEMS_STARTED = 'ACTION_GET_ITEMS_STARTED'
export const ACTION_GET_ITEMS_SUCCESED = 'ACTION_GET_ITEMS_SUCCESED'
export const ACTION_GET_ITEMS_FAILED = 'ACTION_GET_ITEMS_FAILED'

export const ACTION_GET_BRANDS_SUCCESED = 'ACTION_GET_BRANDS_SUCCESED'
export const ACTION_GET_BRANDS_FAILED = 'ACTION_GET_BRANDS_FAILED'

export const ACTION_ADD_BRAND_FILTER = 'ACTION_ADD_BRAND_FILTER'
export const ACTION_DEL_BRAND_FILTER = 'ACTION_DEL_BRAND_FILTER'

export const ACTION_CLEAN_FILTERS = 'ACTION_CLEAN_FILTERS'

export const ACTION_CHANGE_PRICE_MIN_FILTER = 'ACTION_CHANGE_PRICE_MIN_FILTER'
export const ACTION_CHANGE_PRICE_MAX_FILTER = 'ACTION_CHANGE_PRICE_MAX_FILTER'

export const ACTION_SET_SORTED = 'ACTION_SET_SORTED'

export const ACTION_SET_SEARCH_TEXT = 'ACTION_SET_SEARCH_TEXT'

export const ACTION_GET_SEARCH_ITEMS_SUCCESED = 'ACTION_GET_SEARCH_ITEMS_SUCCESED'
export const ACTION_GET_SEARCH_ITEMS_STARTED = 'ACTION_GET_SEARCH_ITEMS_STARTED'
export const ACTION_GET_SEARCH_ITEMS_FAILED = 'ACTION_GET_SEARCH_ITEMS_FAILED'

