export const ACTION_GET_CARD_ITEMS_STARTED = 'ACTION_GET_CARD_ITEMS_STARTED'
export const ACTION_GET_CARD_ITEMS_SUCCESED = 'ACTION_GET_CARD_ITEMS_SUCCESED'
export const ACTION_GET_CARD_ITEMS_FAILED = 'ACTION_GET_CARD_ITEMS_FAILED'

export const ACTION_ADD_CARD_ITEMS_STARTED = 'ACTION_ADD_CARD_ITEMS_STARTED'
export const ACTION_ADD_CARD_ITEMS_SUCCESED = 'ACTION_ADD_CARD_ITEMS_SUCCESED'
export const ACTION_ADD_CARD_ITEMS_FAILED = 'ACTION_ADD_CARD_ITEMS_FAILED'
